language: csharp
dotnet: 2.1.802
mono: none
os:
  - linux
  - osx
solution: Hex.sln
script:
  - dotnet build --configuration CI Hex.sln
  # - dotnet test
cache:
  directories:
    - artifacts
    - docs
